# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

plugins:
  - jekyll-redirect-from

# Site settings
title: "HackIllinois"
description: > # this means to ignore newlines until "email:"
   The HackIllinois blog! Check out what we've been up to.

future: true

email: contact@hackillinois.org
#blog logo
logo: "/assets/images/logo.png"

# blog cover
cover: "/assets/images/cover.jpg"

name: 'HackIllinois Team'
author: 'HackIllinois Team'
author_image: "/assets/images/logo.png"

paginate:	5

url: "http://blog.hackillinois.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@hackillinois'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-46010489-3

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/hackillinois
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/hackillinois
    desc: Connect with us on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/hackillinois
    desc:	Check us out on GitHub
    share_url:
    share_title:
    share_link:
