# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HackIllinois Blog
email: contact@hackillinois.org
description: > # this means to ignore newlines until "baseurl:"
  The HackIllinois blog! Check out what we've been up to.
baseurl: "" # the subpath of your site, e.g. /blog
url: "blog.hackillinois.org" # the base hostname & protocol for your site
twitter_username: hackillinois
github_username:  hackillinois

# Build settings
markdown: kramdown
